// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCah41wnSKeHvVdAF_7vhN_f2W0bMBTwZ4',
    appId: '1:974684756572:web:da7e157b1337cad2572499',
    messagingSenderId: '974684756572',
    projectId: 'fb-auth-riverpod-8db86',
    authDomain: 'fb-auth-riverpod-8db86.firebaseapp.com',
    storageBucket: 'fb-auth-riverpod-8db86.appspot.com',
    measurementId: 'G-EH34XWH6KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW-GiXkmpFbLZaqmNmq9uAquHlfsWKTBo',
    appId: '1:974684756572:android:a0e75027dddaa18c572499',
    messagingSenderId: '974684756572',
    projectId: 'fb-auth-riverpod-8db86',
    storageBucket: 'fb-auth-riverpod-8db86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDasyirx4z9odGomVQCulF94x7p44ykQtw',
    appId: '1:974684756572:ios:c102f1161cc65493572499',
    messagingSenderId: '974684756572',
    projectId: 'fb-auth-riverpod-8db86',
    storageBucket: 'fb-auth-riverpod-8db86.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDasyirx4z9odGomVQCulF94x7p44ykQtw',
    appId: '1:974684756572:ios:c102f1161cc65493572499',
    messagingSenderId: '974684756572',
    projectId: 'fb-auth-riverpod-8db86',
    storageBucket: 'fb-auth-riverpod-8db86.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCah41wnSKeHvVdAF_7vhN_f2W0bMBTwZ4',
    appId: '1:974684756572:web:1aec02d6fb220a34572499',
    messagingSenderId: '974684756572',
    projectId: 'fb-auth-riverpod-8db86',
    authDomain: 'fb-auth-riverpod-8db86.firebaseapp.com',
    storageBucket: 'fb-auth-riverpod-8db86.appspot.com',
    measurementId: 'G-DHD9DX1555',
  );

}